# Generated by Django 2.2.3 on 2019-07-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoralRect',
            fields=[
                ('url', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('x0', models.FloatField()),
                ('x1', models.FloatField()),
                ('y0', models.FloatField()),
                ('y1', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Corals',
            fields=[
                ('url', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('farm', models.CharField(max_length=10)),
                ('server', models.CharField(max_length=20)),
                ('photoid', models.CharField(max_length=50)),
                ('secret', models.CharField(max_length=50)),
            ],
        ),
    ]
